import { z } from "zod";

export const WeatherResponseSchema = z.object({
  lat: z.number(),
  lon: z.number(),
  timezone: z.string(),
  timezone_offset: z.number().int(),
  current: z.object({
    dt: z.number().int(),
    sunrise: z.number().int(),
    sunset: z.number().int(),
    temp: z.number(),
    feels_like: z.number(),
    pressure: z.number().int(),
    humidity: z.number().int(),
    dew_point: z.number(),
    uvi: z.number(),
    clouds: z.number().int(),
    visibility: z.number().int(),
    wind_speed: z.number(),
    wind_deg: z.number().int(),
    weather: z.array(z.object({
      id: z.number().int(),
      main: z.string(),
      description: z.string(),
      icon: z.string(),
    })),
  }),
  hourly: z.array(z.object({
    dt: z.number().int(),
    temp: z.number(),
    feels_like: z.number(),
    pressure: z.number().int(),
    humidity: z.number().int(),
    dew_point: z.number(),
    uvi: z.number(),
    clouds: z.number().int(),
    visibility: z.number().int(),
    wind_speed: z.number(),
    wind_deg: z.number().int(),
    pop: z.number(),
    weather: z.array(z.object({
      id: z.number().int(),
      main: z.string(),
      description: z.string(),
      icon: z.string(),
    })),
  })),
  daily: z.array(z.object({
    dt: z.number().int(),
    sunrise: z.number().int(),
    sunset: z.number().int(),
    moonrise: z.number().int(),
    moonset: z.number().int(),
    moon_phase: z.number(),
    temp: z.object({
      day: z.number(),
      min: z.number(),
      max: z.number(),
      night: z.number(),
      eve: z.number(),
      morn: z.number(),
    }),
    feels_like: z.object({
      day: z.number(),
      night: z.number(),
      eve: z.number(),
      morn: z.number(),
    }),
    pressure: z.number().int(),
    humidity: z.number().int(),
    dew_point: z.number(),
    uvi: z.number(),
    clouds: z.number().int(),
    wind_speed: z.number(),
    wind_deg: z.number().int(),
    pop: z.number(),
    weather: z.array(z.object({
      id: z.number().int(),
      main: z.string(),
      description: z.string(),
      icon: z.string(),
    })),
  })),
});

export type WeatherResponse = z.infer<typeof WeatherResponseSchema>;